### ISSUE TITLE
Pip packaging issue for tpp?

### ISSUE THREAD

**Issue by wmatern** [mad-lab/transit#9]
Hi Dr. Dejesus,

I'm having an issue with starting tpp from the terminal with arguments. I did the following:
$ sudo pip2 install -I tnseq-transit
...
Successfully installed backports.functools-lru-cache-1.5 cycler-0.10.0 kiwisolver-1.0.1 matplotlib-2.2.2 numpy-1.14.3 pillow-5.1.0 pyparsing-2.2.0 python-dateutil-2.7.3 pytz-2018.4 scipy-1.1.0 setuptools-39.2.0 six-1.11.0 subprocess32-3.5.1 tnseq-transit-2.1.2

$ pip2 show tnseq-transit
Name: tnseq-transit
Version: 2.1.2
...

$ cat /usr/bin/tpp
#!/usr/bin/python2

\# -*- coding: utf-8 -*-
import re
import sys

from pytpp.\_\_main__ import main

if \_\_name__ == '\_\_main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    **sys.exit(main())**

I've bolded the problem line. This should be 'sys.exit(main(sys.argv[1:]))' as in src/tpp.py. If I change it then as soon as I do: 
$ sudo pip2 install -I tnseq-transit

It goes back to sys.exit(main()).

So it seems like an issue specific to the pip packaging?

Thanks,

Will

**Comment by mad-lab** [comment]
Yeah, it looks like maybe pip/setuptools has changed how it behaves? Because you are right; it's overwriting the way arguments are passed to the entry_point when you install it as a package and forces it to call main with no arguments. 

I will check in a fix for next release (hopefully within a month). Thank you for noticing this and letting us know!

**Comment by mad-lab** [comment]
Should be fixed in this latest version.
